const { readDiscordToken, logTokenDiagnostic } = require('./config');
const { Client, GatewayIntentBits, Partials } = require('discord.js');
const MAX_DISCORD_LENGTH = 2000;
const contextLimit = Math.max(2, Number(process.env.FORGE_ASSIST_CONTEXT_LIMIT || 12));
const conversations = new Map();
const archivedEventIds = new Set();
const archiveStats = { totalQueries: 0, successfulQueries: 0, failedQueries: 0, attachments: 0, providers: {}, languages: {} };
function keyFor(message) { return `${message.guildId || 'dm'}:${message.channelId}:${message.author.id}`; }
function configuredChannelIds() { return (process.env.FORGE_ASSIST_CHANNEL_IDS || '').split(',').map(x => x.trim()).filter(Boolean); }
function shouldRespond(message, client) { if (message.author.bot) return false; return message.mentions.has(client.user) || Boolean(message.reference?.messageId && message.mentions.has(client.user)) || configuredChannelIds().includes(message.channelId); }
function cleanPrompt(message, client) { return message.content.replace(new RegExp(`<@!?${client.user.id}>`, 'g'), '').trim(); }
function getContext(key) { return conversations.get(key) || []; }
function saveTurn(key, user, assistant) { conversations.set(key, [...getContext(key), { role: 'user', content: user }, { role: 'assistant', content: assistant }].slice(-contextLimit)); }
function languageOf(text = '') { const lower = text.toLowerCase(); if (/[\u0900-\u097f]/.test(text)) return 'Hindi'; if (/\b(bhai|hai|kya|kaise|kyu|kar|ye|mujhe|samjha|bata)\b/.test(lower)) return 'Hinglish'; if (/\b(the|what|why|how|please|explain|error|code)\b/.test(lower)) return 'English'; return 'Other'; }
function splitMessage(text) { const chunks = []; let remaining = String(text || '').trim(); while (remaining.length > MAX_DISCORD_LENGTH) { let cut = remaining.lastIndexOf('\n', MAX_DISCORD_LENGTH); if (cut < 500) cut = remaining.lastIndexOf(' ', MAX_DISCORD_LENGTH); if (cut < 1) cut = MAX_DISCORD_LENGTH; chunks.push(remaining.slice(0, cut)); remaining = remaining.slice(cut).trimStart(); } if (remaining) chunks.push(remaining); return chunks.length ? chunks : ['Forge Assist is temporarily unavailable.']; }
async function askBackend(message, prompt) { const base = (process.env.FORGE_ASSIST_BACKEND_URL || '').replace(/\/$/, ''); if (!base) throw new Error('FORGE_ASSIST_BACKEND_URL is not configured'); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), Number(process.env.FORGE_ASSIST_REQUEST_TIMEOUT_MS || 25000)); try { const response = await fetch(`${base}/api/chat`, { method: 'POST', signal: controller.signal, headers: { 'content-type': 'application/json', 'x-forge-assist-secret': process.env.FORGE_ASSIST_API_SECRET || '' }, body: JSON.stringify({ message: prompt, context: getContext(keyFor(message)) }) }); const data = await response.json().catch(() => ({})); if (!response.ok || typeof data.response !== 'string') throw new Error(data.message || `backend returned ${response.status}`); return { response: data.response, provider: data.provider || 'unknown' }; } finally { clearTimeout(timer); } }
async function postArchive(event) { const base = (process.env.FORGE_ASSIST_BACKEND_URL || '').replace(/\/$/, ''); if (!base || !process.env.TELEGRAM_BOT_TOKEN || !process.env.FORGE_DATA_CENTER_2_CHAT_ID || archivedEventIds.has(event.eventId)) return; archivedEventIds.add(event.eventId); try { const response = await fetch(`${base}/api/assist/events`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-forge-assist-secret': process.env.FORGE_ASSIST_API_SECRET || '' }, body: JSON.stringify(event) }); if (!response.ok) throw new Error(`archive returned ${response.status}`); } catch (error) { archivedEventIds.delete(event.eventId); console.error(`[forge-assist] Telegram archive failed: ${error.message}`); } }
function archiveEvent(message, prompt, success, provider) { const language = languageOf(prompt); archiveStats.totalQueries += 1; if (success) archiveStats.successfulQueries += 1; else archiveStats.failedQueries += 1; archiveStats.providers[provider] = archiveStats.providers[provider] || { success: 0, failure: 0 }; archiveStats.providers[provider][success ? 'success' : 'failure'] += 1; archiveStats.languages[language] = (archiveStats.languages[language] || 0) + 1; archiveStats.attachments += message.attachments.size; const eventId = `${message.id}:${success ? 'success' : 'failure'}`; void postArchive({ eventId, messageId: message.id, guildId: message.guildId || null, userId: message.author.id, username: message.author.username, question: prompt, success, provider, language, timestamp: message.createdAt?.toISOString() || new Date().toISOString(), totalQueries: archiveStats.totalQueries, successfulQueries: archiveStats.successfulQueries, failedQueries: archiveStats.failedQueries, activeConversations: conversations.size, contextMessageCount: getContext(keyFor(message)).length, attachments: [...message.attachments.values()].map(x => ({ id: x.id, url: x.url, filename: x.name, contentType: x.contentType || 'application/octet-stream', size: x.size })) }); }
function createBot() { const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.DirectMessages], partials: [Partials.Channel] }); client.once('ready', () => console.log(`[forge-assist] logged in as ${client.user.tag}`)); client.on('messageCreate', async message => { if (!shouldRespond(message, client)) return; const prompt = cleanPrompt(message, client); if (!prompt) return message.reply('Hey! Ask me something and I’ll help.'); try { await message.channel.sendTyping(); const result = await askBackend(message, prompt); saveTurn(keyFor(message), prompt, result.response); archiveEvent(message, prompt, true, result.provider); let first = true; for (const part of splitMessage(result.response)) { if (first) { await message.reply(part); first = false; } else await message.channel.send(part); } } catch (error) { console.error(`[forge-assist] message handling failed: ${error.message}`); archiveEvent(message, prompt, false, 'unknown'); await message.reply('I’m temporarily unable to reach my AI backend. Please try again in a moment.').catch(replyError => console.error(`[forge-assist] reply failed: ${replyError.message}`)); } }); return client; }
async function startBot({ env = process.env, botFactory = createBot, logger = console } = {}) { const discordToken = readDiscordToken(env); logTokenDiagnostic(discordToken, logger); if (!discordToken) throw new Error('DISCORD_TOKEN is required'); return botFactory().login(discordToken); }
if (require.main === module) { startBot().catch(error => { console.error(`[forge-assist] startup failed: ${error.message}`); process.exitCode = 1; }); }
module.exports = { createBot, startBot, splitMessage, shouldRespond, conversations, archiveEvent, postArchive, archiveStats };
