const TELEGRAM_LIMIT = 4096;
const SCHEMA_VERSION = 1;

function config(env = process.env) {
  if (!env.TELEGRAM_BOT_TOKEN || !env.FORGE_DATA_CENTER_2_CHAT_ID) throw new Error('Telegram Data Center 2 is not configured');
  return { token: env.TELEGRAM_BOT_TOKEN, chatId: env.FORGE_DATA_CENTER_2_CHAT_ID };
}
async function telegram(method, payload, env = process.env) {
  const { token } = config(env);
  const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok || data.ok === false) throw new Error(`Telegram ${method} failed (${response.status})`);
  return data.result;
}
function chunk(text) { const out = []; let rest = String(text); while (rest.length > TELEGRAM_LIMIT) { let cut = rest.lastIndexOf('\n', TELEGRAM_LIMIT); if (cut < 1) cut = rest.lastIndexOf(' ', TELEGRAM_LIMIT); if (cut < 1) cut = TELEGRAM_LIMIT; out.push(rest.slice(0, cut)); rest = rest.slice(cut).trimStart(); } if (rest) out.push(rest); return out; }
function archiveRecord(type, fields) { return ['[FORGE_ASSIST]', `schema_version=${SCHEMA_VERSION}`, `record_type=${type}`, ...Object.entries(fields).map(([key, value]) => `${key}=${JSON.stringify(value ?? null)}`)].join('\n'); }
function parseArchiveRecord(text) { const lines = String(text).split('\n'); if (lines[0] !== '[FORGE_ASSIST]') throw new Error('invalid Forge Assist archive record'); return Object.fromEntries(lines.slice(1).filter(Boolean).map(line => { const index = line.indexOf('='); if (index < 1) throw new Error('invalid Forge Assist archive field'); const key = line.slice(0, index); const value = line.slice(index + 1); try { return [key, JSON.parse(value)]; } catch { return [key, value]; } })); }
function memberRecordText(event) { return archiveRecord(event.memberEventType || 'MEMBER_UPDATED', { discord_user_id: event.userId, username: event.username || null, display_name: event.displayName || null, guild_id: event.guildId || null, first_seen_at: event.firstSeenAt || event.timestamp, last_seen_at: event.timestamp, language: event.language || 'Other', conversation_status: event.mode || 'active', updated_at: event.timestamp }); }
function sessionRecordText(event) { return archiveRecord(event.sessionEventType || 'SESSION_STARTED', { session_id: event.sessionId, discord_user_id: event.userId, guild_id: event.guildId || null, channel_id: event.channelId || null, mode: event.mode || 'private_dm', created_at: event.sessionCreatedAt || event.timestamp, updated_at: event.timestamp }); }
function conversationRecordText(event) { return archiveRecord('CONVERSATION_RECORD', { event_id: event.eventId, session_id: event.sessionId, discord_user_id: event.userId, guild_id: event.guildId || null, channel_id: event.channelId || null, mode: event.mode || 'private_dm', timestamp: event.timestamp, role: 'user', question: event.question, language: event.language || 'Other', provider: event.provider || 'unknown', success: Boolean(event.success), response: event.response || 'Unavailable', attachment_ids: (event.attachments || []).map(item => item.id || item.filename) }); }
function statsText(event) { return archiveRecord('EVENT_RECORD', { event_id: event.eventId, discord_user_id: event.userId, guild_id: event.guildId || null, session_id: event.sessionId, total_queries: event.totalQueries ?? null, successful_queries: event.successfulQueries ?? null, failed_queries: event.failedQueries ?? null, provider: event.provider || 'unknown', language: event.language || 'Other', active_conversations: event.activeConversations ?? null, context_message_count: event.contextMessageCount ?? null, timestamp: event.timestamp }); }
function onboardingRecordText(event) { return archiveRecord(event.recordType || 'MEMBER_ONBOARDING', { event_id: event.eventId, discord_user_id: event.discordUserId, guild_id: event.guildId, guild_name: event.guildName, username: event.username, global_name: event.globalName, display_name: event.displayName, avatar: event.avatar, account_created_at: event.accountCreatedAt, joined_at: event.joinedAt, roles: event.roles || [], onboarding: event.onboarding || {}, profile: event.profile || {}, member_flags: event.memberFlags, metadata: event.metadata || {} }); }
async function sendRecord(text, chatId, env) { for (const part of chunk(text)) await telegram('sendMessage', { chat_id: chatId, text: part }, env); }
async function archiveEvent(event, env = process.env) { const { chatId } = config(env); if (event.type === 'MEMBER_ONBOARDING') { await sendRecord(onboardingRecordText(event), chatId, env); return { archived: true, eventId: event.eventId }; } if (event.memberEventType) await sendRecord(memberRecordText(event), chatId, env); if (event.sessionEventType) await sendRecord(sessionRecordText(event), chatId, env); await sendRecord(conversationRecordText(event), chatId, env); for (const attachment of event.attachments || []) { try { await telegram('sendDocument', { chat_id: chatId, document: attachment.url, caption: `Forge Assist attachment\n${attachment.filename}\nType: ${attachment.contentType || 'unknown'}\nSize: ${attachment.size || 'unknown'} bytes\nDiscord message: ${event.messageId}\nSession: ${event.sessionId}\nEvent: ${event.eventId}` }, env); } catch (error) { console.error(`[forge-assist] Telegram attachment unavailable: ${error.message}`); await telegram('sendMessage', { chat_id: chatId, text: `Attachment archive failed\nfilename=${JSON.stringify(attachment.filename)}\nattachment_id=${JSON.stringify(attachment.id)}\nevent_id=${JSON.stringify(event.eventId)}` }, env).catch(() => {}); } } await sendRecord(statsText(event), chatId, env); return { archived: true, eventId: event.eventId }; }
module.exports = { archiveEvent, config, chunk, archiveRecord, parseArchiveRecord, memberRecordText, sessionRecordText, conversationRecordText, statsText, onboardingRecordText, SCHEMA_VERSION };
